### ISSUE TITLE
Can't configure buttons on Stream Deck subpages (using the folder action)

### ISSUE THREAD

**Issue by TahoeJimbo** [Mazecreator/udcontrol-streamdeck#1]
When I configure more than one node button on a subpage, **all** previously defined buttons on the subpage get the new button's node address. 

This doesn't happen on the home page.

Thanks for making this.  Saved me the time I was going to spend to make my own. :-)

**Comment by jackiemeck1** [comment]
I'm having the same issue.  And I can't get the node to turn a light on/off.  No response.

**Comment by Mazecreator** [comment]
Does this still seem to be a problem?  I don't seem to see this issue when I add a Node to a subpage where I have configured all my Nodes.

Do you have a work-around for you to use the Node feature?

**Comment by Mazecreator** [comment]
No response, Closing Issue.
