### ISSUE TITLE
Feature: Support Scenes

### ISSUE THREAD

**Issue by brockpalen** [Mazecreator/udcontrol-streamdeck#3]
I have a number of scenes I would like to control directly without making a program first.

Is this possible as a future request?

**Comment by Mazecreator** [comment]
According to the REST API, Scenes and Devices should be the same, So control it like a light. I haven't worked on this in a while, but if you can find the sceneID use that as it if is a device and it should work.

https://wiki.universal-devices.com/index.php?title=ISY_Developers:API:REST_Interface

**Comment by brockpalen** [comment]
That does appear to work.  The fractional lighting 25% etc doesn't appear to work but for what I wanted it's good enough.  Thanks!  Can close,
